<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="primitive_mobile_platform">

  <!-- resolve prefix variable (useful for multi robot) -->
  <xacro:include filename="$(find chargepal_description)/urdf/utils/prefix.urdf.xacro" />
  <xacro:include filename="$(find chargepal_description)/urdf/utils/common_properties.urdf.xacro" />

  <!-- object properties -->
  <xacro:property name="mobile_base_mass" value="100.0" />
  <xacro:property name="mobile_base_length" value="0.8" />
  <xacro:property name="mobile_base_width" value="0.58" />
  <xacro:property name="mobile_base_height" value="0.4" />
  
  <xacro:property name="tower_mass" value="50.0" />
  <xacro:property name="tower_length" value="0.25" />
  <xacro:property name="tower_height" value="0.5" />
  
  <xacro:property name="battery_mass" value="300.0" />
  <xacro:property name="battery_length" value="0.55" />
  <xacro:property name="battery_width" value="0.795" />
  <xacro:property name="battery_height" value="0.4" />

    <!-- start kinematic chain -->
  <link name="world"/>
  <joint name="${prefix}world_joint" type="fixed">
    <parent link="world" />
    <child link="${prefix}mobile_base_link" />
    <origin rpy="0.0 0.0 0.0" xyz="${-0.5*mobile_base_length+0.5*tower_length} 0.0 ${0.5*mobile_base_height}" />
  </joint>
  <link name="${prefix}mobile_base_link">
    <xacro:box_inertial_ x="${mobile_base_length}" y="${mobile_base_width}" z="${mobile_base_height}" mass="${mobile_base_mass}">
      <origin xyz="0 0 ${mobile_base_height}" rpy="0 0 0" />
    </xacro:box_inertial_>
    <visual>
      <xacro:insert_block name="material_grey" />
      <orign rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0" />
      <geometry>
        <box size="${mobile_base_length} ${mobile_base_width} ${mobile_base_height}" />
      </geometry>
    </visual>
    <collision>
      <orign rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0" />
      <geometry>
        <box size="${mobile_base_length} ${mobile_base_width} ${mobile_base_height}" />
      </geometry>
    </collision>
  </link>

  <joint name="${prefix}tower_joint" type="fixed">
    <parent link="${prefix}mobile_base_link" />
    <child link="${prefix}tower_link" />
    <origin rpy="0.0 0.0 0.0" xyz="${0.5*mobile_base_length-0.5*tower_length} 0.0 ${0.5*mobile_base_height+0.5*tower_height}" />
  </joint>
  <link name="${prefix}tower_link">
    <xacro:box_inertial_ x="${tower_length}" y="${mobile_base_width}" z="${tower_height}" mass="${tower_mass}">
      <origin xyz="0 0 ${tower_height}" rpy="0 0 0" />
    </xacro:box_inertial_>
    <visual>
      <xacro:insert_block name="material_grey" />
      <orign rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0" />
      <geometry>
        <box size="${tower_length} ${mobile_base_width} ${tower_height}" />
      </geometry>
    </visual>
    <collision>
      <orign rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0" />
      <geometry>
        <box size="${tower_length} ${mobile_base_width} ${tower_height}" />
      </geometry>
    </collision>
  </link>

  <joint name="${prefix}battery_joint" type="fixed">
    <parent link="${prefix}mobile_base_link" />
    <child link="${prefix}battery_link" />
    <origin rpy="0.0 0.0 0.0" xyz="${-0.5*tower_length - 0.025} 0.0 ${0.5*mobile_base_height+0.5*battery_height}" />
  </joint>
  <link name="${prefix}battery_link">
    <xacro:box_inertial_ x="${battery_length}" y="${battery_width}" z="${battery_height}" mass="${battery_mass}">
      <origin xyz="0 0 ${battery_height}" rpy="0 0 0" />
    </xacro:box_inertial_>
    <visual>
      <xacro:insert_block name="material_aluminium" />
      <orign rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0" />
      <geometry>
        <box size="${battery_length} ${battery_width} ${battery_height}" />
      </geometry>
    </visual>
    <collision>
      <orign rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0" />
      <geometry>
        <box size="${battery_length} ${battery_width} ${battery_height}" />
      </geometry>
    </collision>
  </link>


  <!-- colorize platform -->
  <gazebo reference="${prefix}mobile_base_link">
    <material>Gazebo/DarkGrey</material>
  </gazebo>
  <gazebo reference="${prefix}tower_link">
    <material>Gazebo/DarkGrey</material>
  </gazebo>
  <gazebo reference="${prefix}battery_link">
    <material>Gazebo/Grey</material>
  </gazebo>

</robot>
