<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="primitive_adapter_station">

  <!-- Macros -->
  <xacro:include filename="$(find chargepal_description)/urdf/utils/chargepal_material.urdf.xacro" />
  <xacro:include filename="$(find chargepal_description)/urdf/utils/chargepal_inertial.urdf.xacro" />
  <xacro:include filename="$(find chargepal_description)/urdf/utils/chargepal_common.urdf.xacro" />

  <!-- object properties -->
  <xacro:property name="station_width" value="0.25" />
  <xacro:property name="socket_size" value="0.07" />
  <xacro:property name="socket_height" value="1.20" />
  
  <xacro:property name="panel_thickness" value="${0.5*(station_width-socket_size)}" />
  
  <!-- start kinematic chain -->
  <link name="world" />  
  <joint name="world_joint" type="fixed">
    <parent link="world" />
    <child link="low_body_link" />
    <origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 ${0.5*(socket_height-0.5*socket_size)}" />
  </joint>
  <link name="low_body_link">
    <xacro:inertial_box x="${station_width}" y="${station_width}" z="${socket_height - 0.5*socket_size}" mass="50.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:inertial_box>
    <visual>
      <xacro:insert_block name="material_grey" />
      <orign rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0" />
      <geometry>
        <box size="${station_width} ${station_width} ${socket_height - 0.5*socket_size}" />
      </geometry>
    </visual>
    <collision>
      <orign rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0" />
      <geometry>
        <box size="${station_width} ${station_width} ${socket_height - 0.5*socket_size}" />
      </geometry>
    </collision>
  </link>

  <joint name="left_panel_joint" type="fixed">
    <parent link="low_body_link" />
    <child link="left_panel_link" />
    <origin rpy="0.0 0.0 0.0" xyz="${-0.25*(station_width+socket_size)} 0.0 ${0.5*socket_height + 0.25*socket_size}" />
  </joint>
  <link name="left_panel_link">
    <xacro:inertial_box x="${panel_thickness}" y="${station_width}" z="${socket_size}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:inertial_box>
    <visual>
      <xacro:insert_block name="material_grey" />
      <orign rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0" />
      <geometry>
        <box size="${panel_thickness} ${station_width} ${socket_size}" />
      </geometry>
    </visual>
    <collision>
      <orign rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0" />
      <geometry>
        <box size="${panel_thickness} ${station_width} ${socket_size}" />
      </geometry>
    </collision>
  </link>
  
  <joint name="right_panel_joint" type="fixed">
    <parent link="low_body_link" />
    <child link="right_panel_link" />
    <origin rpy="0.0 0.0 0.0" xyz="${0.25*(station_width+socket_size)} 0.0 ${0.5*socket_height + 0.25*socket_size}" />
  </joint>
  <link name="right_panel_link">
    <xacro:inertial_box x="${panel_thickness}" y="${station_width}" z="${socket_size}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:inertial_box>
    <visual>
      <xacro:insert_block name="material_grey" />
      <orign rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0" />
      <geometry>
        <box size="${panel_thickness} ${station_width} ${socket_size}" />
      </geometry>
    </visual>
    <collision>
      <orign rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0" />
      <geometry>
        <box size="${panel_thickness} ${station_width} ${socket_size}" />
      </geometry>
    </collision>
  </link>
  
  <joint name="top_panel_joint" type="fixed">
    <parent link="low_body_link"/>
    <child link="top_panel_link"/>
    <origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 ${0.25*(2*socket_height + 2*socket_size + station_width)}"/>
  </joint>
  <link name="top_panel_link">
    <xacro:inertial_box x="${station_width}" y="${station_width}" z="${panel_thickness}" mass="10.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:inertial_box>
    <visual>
      <xacro:insert_block name="material_grey" />
      <orign rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0" />
      <geometry>
        <box size="${station_width} ${station_width} ${panel_thickness}" />
      </geometry>
    </visual>
    <collision>
      <orign rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0" />
      <geometry>
        <box size="${station_width} ${station_width} ${panel_thickness}" />
      </geometry>
    </collision>
  </link>
  
  <!-- ########## TARGET ############ -->
  <!-- virtual target reference frame -->
  <xacro:chargepal_virtual_joint 
    joint_name="target_ref_frame_joint" 
    type="fixed"
    parent="world"
    child="target_reference_frame"
    joint_axis_xyz="0 0 0"
    joint_origin_xyz="0 ${-station_width/2} ${socket_height}"
    joint_origin_rpy="${pi/2} 0 ${pi}"
    joint_lower_limit="0"
    joint_upper_limit="0"
  />
  <xacro:chargepal_virtual_link link_name="target_reference_frame" />

  <!-- Add three (for each axis) additional virtual frames for reward calculation -->
  <xacro:chargepal_virtual_joint
    joint_name="virt_tgt_frame_x_joint" 
    type="fixed"
    parent="target_reference_frame"
    child="virt_tgt_frame_x"
    joint_axis_xyz="0 0 0"
    joint_origin_xyz="1 0 0"
    joint_origin_rpy="0 0 0"
    joint_lower_limit="0"
    joint_upper_limit="0"
  />
  <xacro:chargepal_virtual_link link_name="virt_tgt_frame_x" />

  <xacro:chargepal_virtual_joint
    joint_name="virt_tgt_frame_y_joint" 
    type="fixed"
    parent="target_reference_frame"
    child="virt_tgt_frame_y"
    joint_axis_xyz="0 0 0"
    joint_origin_xyz="0 1 0"
    joint_origin_rpy="0 0 0"
    joint_lower_limit="0"
    joint_upper_limit="0"
  />
  <xacro:chargepal_virtual_link link_name="virt_tgt_frame_y" />

  <xacro:chargepal_virtual_joint
    joint_name="virt_tgt_frame_z_joint" 
    type="fixed"
    parent="target_reference_frame"
    child="virt_tgt_frame_z"
    joint_axis_xyz="0 0 0"
    joint_origin_xyz="0 0 1"
    joint_origin_rpy="0 0 0"
    joint_lower_limit="0"
    joint_upper_limit="0"
  />
  <xacro:chargepal_virtual_link link_name="virt_tgt_frame_z" />


  <!-- colorize adapter station -->
  <gazebo reference="low_body_link">
    <material>Gazebo/Grey</material>
  </gazebo>
  <gazebo reference="left_panel_link">
    <material>Gazebo/Grey</material>
  </gazebo>
  <gazebo reference="right_panel_link">
    <material>Gazebo/Grey</material>
  </gazebo>
  <gazebo reference="top_panel_link">
    <material>Gazebo/Grey</material>
  </gazebo>
  
</robot>
